CREATE TABLE Push_Subscriptions (
  ID_Subscription INT PRIMARY KEY IDENTITY(1,1),
  ID_Usuario INT FOREIGN KEY REFERENCES Usuarios(ID_Usuario) ON DELETE CASCADE,
  Endpoint VARCHAR(MAX) NOT NULL,
  P256dh VARCHAR(MAX) NOT NULL,
  Auth VARCHAR(MAX) NOT NULL,
  CriadoEm DATETIME DEFAULT GETDATE()
);
GO
